In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#cargar Data
customers_aditionals = pd.read_csv("bank-additional.csv")
pd.options.display.max_columns=30
customers_aditionals.head(3)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b

Ejecutamos una serie de comandos basicos para tener una idea general del data set antes de comenzar a trabajar

In [3]:
customers_aditionals.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

In [4]:

customers_aditionals.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [5]:
customers_aditionals['age'].value_counts()

age
31.0    1810
33.0    1704
32.0    1672
36.0    1649
34.0    1608
        ...
98.0       2
89.0       2
95.0       1
87.0       1
94.0       1
Name: count, Length: 78, dtype: int64

comprobamos que las filas donde AGE no tienen datos sean de utilidad, ya qmue representan un 12% de nuestro data set y puede afectar gravemente los resultados

In [6]:
customers_aditionals[customers_aditionals['age'].isna()].describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,5120.000000,0.0,4015.000000,5008.000000,5008.000000,5120.000000,5120.000000,5120.000000,5120.000000,5120.000000,5120.000000,5120.000000
mean,20743.986328,NaN,0.000249,0.529952,0.154153,255.099805,2.514258,961.757422,0.179688,0.065527,36.829637,-96.105107
std,11832.397742,NaN,0.015782,0.499152,0.361132,251.670326,2.663778,188.699063,0.515948,1.577635,7.270436,16.902776
min,0.000000,NaN,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,-3.400000,24.403000,-124.962000
25%,10588.250000,NaN,0.000000,0.000000,0.000000,101.000000,1.000000,999.000000,0.000000,-1.800000,30.424000,-110.968750
50%,20944.500000,NaN,0.000000,1.000000,0.000000,180.000000,2.000000,999.000000,0.000000,1.100000,36.827000,-96.029500
75%,30950.750000,NaN,0.000000,1.000000,0.000000,311.000000,3.000000,999.000000,0.000000,1.400000,43.160750,-81.426250
max,41187.000000,NaN,1.000000,1.000000,1.000000,3284.000000,31.000000,999.000000,6.000000,1.400000,49.383000,-66.937000

In [7]:
customers_aditionals[["housing","loan"]]

       housing  loan
0          0.0   0.0
1          0.0   0.0
2          1.0   0.0
3          0.0   0.0
4          0.0   1.0
...        ...   ...
42995      0.0   0.0
42996      1.0   1.0
42997      1.0   0.0
42998      0.0   0.0
42999      0.0   1.0

[43000 rows x 2 columns]

In [8]:
customers_aditionals[customers_aditionals['education'].isna()].head(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
7,7,NaN,blue-collar,MARRIED,NaN,NaN,0.0,0.0,telephone,217,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,25-septiembre-2017,46.871,-122.235,87fdc08b-30ae-4dab-803f-561ecdf27ff0
10,10,41.0,blue-collar,MARRIED,NaN,NaN,0.0,0.0,telephone,55,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,30-noviembre-2015,43.616,-90.902,8d700df5-0c33-4517-8cf8-92e1c92c9c12
26,26,NaN,technician,MARRIED,NaN,0.0,1.0,0.0,telephone,93,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,25-septiembre-2016,44.446,-74.218,cbf9c247-762f-40f9-a351-a7e686ac7488
30,30,46.0,admin.,MARRIED,NaN,0.0,0.0,0.0,telephone,348,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,20-diciembre-2019,46.952,-97.482,61bec99d-c1d2-4231-aa6a-37a002c9af42
31,31,59.0,technician,MARRIED,NaN,0.0,1.0,0.0,telephone,386,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-abril-2019,27.676,-74.451,9eaba08c-51a8-477f-93b6-ad65fb0b6f03

In [9]:
customers_aditionals['education'].unique()

<StringArray>
[           'basic.4y',         'high.school',            'basic.6y',
            'basic.9y', 'professional.course',                   nan,
   'university.degree',          'illiterate']
Length: 8, dtype: str

In [10]:
customers_aditionals.isnull().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

In [11]:
customers_aditionals["job"].unique()

<StringArray>
[    'housemaid',      'services',        'admin.',   'blue-collar',
    'technician',       'retired',    'management',    'unemployed',
 'self-employed',             nan,  'entrepreneur',       'student']
Length: 12, dtype: str

In [12]:
customers_aditionals[customers_aditionals['euribor3m'].isnull()].head(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
9,9,25.0,services,SINGLE,high.school,0.0,1.0,0.0,telephone,50,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2-noviembre-2016,30.297,-117.382,ea6b7d04-9271-4c0a-a01f-07795d164aba
11,11,25.0,services,SINGLE,high.school,0.0,1.0,0.0,telephone,222,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,17-abril-2016,49.118,-85.121,ca5c0d7a-8bbd-42b3-8351-1074c5be011a

In [13]:
customers_aditionals['euribor3m'].unique()

<StringArray>
['4,857',     nan, '4,856', '4,855', '4,859',  '4,86', '4,858', '4,864',
 '4,865', '4,866',
 ...
  '1,05', '1,049', '1,046', '1,041',  '1,04', '1,039', '1,035',  '1,03',
 '1,031', '1,028']
Length: 310, dtype: str

In [14]:
customers_aditionals["date"]

0             2-agosto-2019
1        14-septiembre-2016
2           15-febrero-2019
3         29-noviembre-2015
4             29-enero-2017
                ...
42995       13-octubre-2015
42996         17-marzo-2018
42997    15-septiembre-2016
42998    23-septiembre-2019
42999      6-noviembre-2019
Name: date, Length: 43000, dtype: str

In [15]:
customers_aditionals["cons.price.idx"].unique()

<StringArray>
['93,994',      nan, '94,465', '93,918', '93,444', '93,798',   '93,2',
 '92,756', '92,843', '93,075', '92,893', '92,963', '92,469', '92,201',
 '92,379', '92,431', '92,649', '92,713', '93,369', '93,749', '93,876',
 '94,055', '94,215', '94,027', '94,199', '94,601', '94,767']
Length: 27, dtype: str

comenzamos la transformacion, quitando, rellenando o eliminando filas que tengan datos incompletos o no validos

rellenamos valores de trabajo y educacion con valores utilizables como "se abstiene" ya que las filas tienen valores validos

rellenamos datos como tasas de interes creditos con valores neutrales

In [16]:
customers_aditionals["job"] = customers_aditionals["job"].fillna("abstains")
customers_aditionals["default"] = customers_aditionals["default"].fillna(0)
customers_aditionals[["housing","loan"]] = customers_aditionals[["housing","loan"]].fillna(0)
customers_aditionals['education'] = customers_aditionals['education'].fillna("abstains")
customers_aditionals['marital'] = customers_aditionals['marital'].fillna("abstains")
customers_aditionals['euribor3m'] = customers_aditionals['euribor3m'].fillna(0)

#limpiamos y cambiamos de tipo la columna de indice de precios
customers_aditionals = customers_aditionals.dropna(subset=['cons.price.idx'])
customers_aditionals['cons.price.idx'] = customers_aditionals['cons.price.idx'].str.replace(',', '.', regex=False)
customers_aditionals['cons.price.idx'] = pd.to_numeric(customers_aditionals['cons.price.idx'], errors='coerce')
#cambiamos el tipo de dato de las columnas Cons.conf eribor3m nr.employed
for col in ['cons.conf.idx', 'euribor3m', 'nr.employed']:
    customers_aditionals[col] = customers_aditionals[col].astype(str).str.replace(',', '.', regex=False)
    customers_aditionals[col] = pd.to_numeric(customers_aditionals[col], errors='coerce')

customers_aditionals[['cons.price.idx','cons.conf.idx','euribor3m','nr.employed']].dtypes

cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
dtype: object

In [17]:
#Segmentar por edad, dejando los NaN como 'Sin dato' ---
bins = [0, 18, 30, 45, 60, 100]
labels = ['0-18', '19-30', '31-45', '46-60', '60+']

customers_aditionals['grupo_edad'] = pd.cut(customers_aditionals['age'], bins=bins, labels=labels)
customers_aditionals['grupo_edad'] = customers_aditionals['grupo_edad'].astype(str)
customers_aditionals['grupo_edad'] = customers_aditionals['grupo_edad'].replace('nan', 'Sin dato')

In [18]:
#eliminamos datos faltantes ya que es una porcion pequeña del data set
customers_aditionals = customers_aditionals.dropna(subset=['date'])

#transformamos nuestra fecha en valores utilizables
meses = {
    'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
    'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
    'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
}

def convertir_fecha(fecha_str):
    dia, mes, año = fecha_str.split('-')
    return f"{dia}-{meses[mes.lower()]}-{año}"

customers_aditionals['date'] = customers_aditionals['date'].apply(convertir_fecha)

#Convertir a datetime
customers_aditionals['date'] = pd.to_datetime(customers_aditionals['date'], format='%d-%m-%Y')

In [19]:
print(customers_aditionals['date'].dtype)
customers_aditionals['date'].head()

datetime64[us]

0   2019-08-02
1   2016-09-14
2   2019-02-15
3   2015-11-29
4   2017-01-29
Name: date, dtype: datetime64[us]

In [20]:
customers_aditionals.isnull().sum()

Unnamed: 0           0
age               5030
job                  0
marital              0
education            0
default              0
housing              0
loan                 0
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
date                 0
latitude             0
longitude            0
id_                  0
grupo_edad        5030
dtype: int64

In [21]:
#Exportaremos el CSV limpio para trabajar en una sesion en blanco
customers_aditionals.to_csv(
    'Datos_Limpios.csv',
    index=False,          # no incluir el índice del DataFrame
    sep=',',              
    encoding='utf-8-sig', 
    header=True           # incluir (o no) los nombres de columna
)